In [1]:
import numpy as np

In [2]:
# Program to print matrix in Zig-zag pattern
# 1 2 4 7 5 3 6 8 9
matrix =[[ 0,  1,  2,  3,4],
        [ 5,  6,  7,8,9],
        [ 10, 11,12, 13,14],
        [  15,16,17,18,19],
         [  20,21,22,23,24]       
        ]
rows=5
columns=5

solution=[[] for i in range(rows+columns-1)]

for i in range(rows):
    for j in range(columns):
        sum=i+j
        if(sum%2 ==0):
            #add at beginning
            solution[sum].insert(0,matrix[i][j])
           
        else:

#add at end of the list
            solution[sum].append(matrix[i][j])
# print the solution as it as
# for i in solution:
#     for j in i:
#         print(j,end=" ")
print(solution)

[[0], [1, 5], [10, 6, 2], [3, 7, 11, 15], [20, 16, 12, 8, 4], [9, 13, 17, 21], [22, 18, 14], [19, 23], [24]]


In [3]:
a=[[0], [1, 5], [10, 6, 2], [3, 7, 11, 15], [20, 16, 12, 8, 4], [9, 13, 17, 21], [22, 18, 14], [19, 23], [24]]
rows=5
columns=5
matrix=np.zeros((rows,columns))
s=0
for i in a:
    s+=1
    z=0
    for j in range(rows):
        for k in range(columns):
            if j+k==s-1 and (j+k==0 or (j+k)%2!=0):  
                matrix[j][k]=i[z]
                z+=1
            elif j+k==s-1 and (j+k)%2==0:
                matrix[k][j]=i[z]
                z+=1

print(matrix)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


In [4]:
matrix =np.array([[ 0,  1,  2,  3],
         [ 5,  6,  7,8],
         [ 10, 11,12, 13],
         [  15,16,17,18],
         [  20,21,22,23],
         [  20,21,22,23],
         [  20,21,22,23],
         ])

In [5]:
matrix

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23],
       [20, 21, 22, 23],
       [20, 21, 22, 23]])

In [6]:
def zigZag(mat):
    J=0
    N = []
    sh = mat.shape[0]+mat.shape[1]-1
    for i in range(sh,-sh-1,-1):
        D = np.diagonal(np.fliplr(mat),i)
        if J%2:
            N.extend(np.flip(D))
        else:
            N.extend(D)
        J+=1
    return N

In [7]:
matrix

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23],
       [20, 21, 22, 23],
       [20, 21, 22, 23]])

In [8]:
Z = zigZag(matrix)

In [9]:
print(Z)

[0, 1, 5, 10, 6, 2, 3, 7, 11, 15, 20, 16, 12, 8, 13, 17, 21, 20, 20, 21, 22, 18, 23, 22, 21, 22, 23, 23]


In [11]:
def segm_zigZag_L(matrix):
    j = 0
    NN = []
    g = matrix.shape[0]-matrix.shape[1]+1

    for i in np.concatenate((np.arange(1,matrix.shape[1]),np.repeat([matrix.shape[1]],g),np.arange(matrix.shape[1]-1,0,-1))):
        NN.append(Z[j:j+i])
        j += i
    return NN

In [12]:
segm_zigZag_L(matrix)

[[0],
 [1, 5],
 [10, 6, 2],
 [3, 7, 11, 15],
 [20, 16, 12, 8],
 [13, 17, 21, 20],
 [20, 21, 22, 18],
 [23, 22, 21],
 [22, 23],
 [23]]